### ISSUE TITLE
LockException when using cluster mode 

### ISSUE THREAD

**Issue by gustavlarson** [MEDIARITHMICS/liquibase-clickhouse#23]
When running using cluster mode and clickhouse-jdbc 0.3.2-patch11 I consistently see the following exception in the log:

```
2022-12-05 16:51:31.847 ERROR 68398 --- [           main] liquibase                                : Could not release lock

liquibase.exception.LockException: liquibase.exception.LockException: Did not update change log lock correctly.

-1 rows were updated instead of the expected 1 row using executor liquibase.executor.jvm.JdbcExecutor there are 1 rows in the table
	at liquibase.lockservice.StandardLockService.releaseLock(StandardLockService.java:394) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Liquibase.lambda$update$1(Liquibase.java:306) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Scope.lambda$child$0(Scope.java:180) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Scope.child(Scope.java:189) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Scope.child(Scope.java:179) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Scope.child(Scope.java:158) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Liquibase.runInScope(Liquibase.java:2447) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:236) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.Liquibase.update(Liquibase.java:221) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:328) ~[liquibase-core-4.17.1.jar:na]
	at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:283) ~[liquibase-core-4.17.1.jar:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.5.jar:2.7.5]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.5.jar:2.7.5]
	...
Caused by: liquibase.exception.LockException: Did not update change log lock correctly.
```

I suspect that this is due to the `ALTER TABLE UPDATE` mutation is running asynchronously. In order for the query to return the number of affected rows the `mutations_sync` setting needs to be 1 or 2: https://clickhouse.com/docs/en/operations/settings/settings/#mutations_sync

I think that the best solution would be to add this setting in the SQL query. Will soon prepare a PR.

**Comment by davisdevs** [comment]
For anyone who might be facing this issue in 2025...

If you run liquibase with `--log-level=fine`, you will see that in cluster mode, the unlock command is ran with `ALTER TABLE... ON CLUSTER` which does not return the number of affected rows compared to `ALTER TABLE...`. The number of updated rows are used by liquibase [StandardLockService](https://github.com/liquibase/liquibase/blob/bb785282793b7f9980538a789ebb1ed8ad2d1f22/liquibase-core/src/main/java/liquibase/lockservice/StandardLockService.java#L373) to determine successful lock acquire/release. Changing `mutations_sync` would not return rows updated data for `ALTER TABLE ... ON CLUSTER` statements.

A very dumb workaround is to run `liquibase status` with a valid cluster config file to create tracking tables with `ON CLUSTER` clause. Once the tracking tables are created as ReplicatedMergeTree, remove `liquibaseClickhouse.conf` and run other liquibase commands so that the lock acquire/release will work properly. This is because `ALTER` and `INSERT` statements will be replicated automatically to other nodes
